// Generated by scripts/embed.ts. Do not edit.
//
// This committed placeholder is what a clean checkout type-checks against. The real version,
// listing every file of the web build, is written during `bun run compile`, starts with
// `@ts-nocheck`, and is a build artifact: restore this placeholder before committing
// (`git checkout apps/server/src/embedded.gen.ts`).
//
// With an empty map, `static.ts` falls back to serving `apps/server/public` from disk.
export const EMBEDDED_ASSETS: Record<string, string> = {};
