// Generated by scripts/embed.ts. Do not edit.
// 4 file(s) from the web build, embedded into the compiled binary.
import asset0 from "../public/index.html" with { type: "file" };
import asset1 from "../public/assets/index-C5UUYcQr.css" with { type: "file" };
import asset2 from "../public/assets/index-CldPv78P.js" with { type: "file" };
import asset3 from "../public/favicon.svg" with { type: "file" };

/** Served path -> path of the embedded file inside the executable. */
export const EMBEDDED_ASSETS: Record<string, string> = {
  "index.html": asset0,
  "assets/index-C5UUYcQr.css": asset1,
  "assets/index-CldPv78P.js": asset2,
  "favicon.svg": asset3,
};
