/**
 * Generates `src/embedded.gen.ts`, which imports every file of the built web UI with
 * `with { type: "file" }`. `bun build --compile` bundles those into the executable, so the
 * binary serves the UI with no `public/` directory next to it.
 *
 * Run after the web build and before compiling: see the root `compile` script.
 */
import { readdirSync, statSync, writeFileSync } from "node:fs";
import { join, posix, relative } from "node:path";

const PUBLIC_DIR = join(import.meta.dir, "..", "public");
const OUT_FILE = join(import.meta.dir, "..", "src", "embedded.gen.ts");

function walk(dir: string): string[] {
  const out: string[] = [];
  for (const entry of readdirSync(dir)) {
    const full = join(dir, entry);
    if (statSync(full).isDirectory()) out.push(...walk(full));
    else out.push(full);
  }
  return out;
}

let files: string[] = [];
try {
  files = walk(PUBLIC_DIR);
} catch {
  console.error(`[embed] ${PUBLIC_DIR} not found — run the web build first.`);
  process.exit(1);
}

const entries = files.map((absolute, index) => ({
  ident: `asset${index}`,
  // Served path, always POSIX-style regardless of host OS.
  served: posix.join(...relative(PUBLIC_DIR, absolute).split(/[\\/]/)),
  importPath: posix.join("..", "public", ...relative(PUBLIC_DIR, absolute).split(/[\\/]/)),
}));

const source = `// @ts-nocheck — generated by scripts/embed.ts. Do not edit, do not commit.
// The bundler resolves these asset imports; TypeScript has no declarations for them, and the
// file is rewritten on every build, so it is excluded from type checking.
// ${entries.length} file(s) from the web build, embedded into the compiled binary.
${entries.map((e) => `import ${e.ident} from "${e.importPath}" with { type: "file" };`).join("\n")}

/** Served path -> path of the embedded file inside the executable. */
export const EMBEDDED_ASSETS: Record<string, string> = {
${entries.map((e) => `  ${JSON.stringify(e.served)}: ${e.ident},`).join("\n")}
};
`;

writeFileSync(OUT_FILE, source);
console.log(`[embed] wrote ${entries.length} asset(s) to ${relative(process.cwd(), OUT_FILE)}`);
